[tool.poetry]
name = "auto-mlops"
version = "0.1.8"
description = "Deploy your model in one line of code"
authors = ["Datarmada <contact@datarmada.com>"]

[tool.poetry.dependencies]
python="^3.6"
requests = "^2.23.0"
cloudpickle = "^1.3.0"
scikit-learn = "^0.22.1"
